### ISSUE TITLE
Maven Central publish

### ISSUE THREAD

**Issue by soywiz** [krzema12/PlotAssert#24]
Could you publish the artifact to Central?

Related issue: https://github.com/korlibs/korge/issues/345

I have updated the easy plugin already to support central: https://github.com/korlibs/easy-kotlin-mpp-gradle-plugin/releases/tag/v0.14.3

**Comment by soywiz** [comment]
Environment/secrets required for it to work on CI:

https://github.com/korlibs/klock/blob/9e47409d6919085d0ce560ff32f0995384edeff4/.github/workflows/DEPLOY.yml#L12-L15
```
ORG_GRADLE_PROJECT_signingKey // GPG key in ASCII armor format
ORG_GRADLE_PROJECT_signingPassword  
SONATYPE_USERNAME
SONATYPE_PASSWORD
```

https://github.com/korlibs/klock/blob/9e47409d6919085d0ce560ff32f0995384edeff4/.github/workflows/DEPLOY.yml#L49

It can use environment variables for `CI`, or read it from `gradle.properties`.

Proper format (with escaped `\n`) for this to put in `~/.gradle/gradle.properties`:

```
gpg --armor --export-secret-keys foobar@example.com | awk 'NR == 1 { print "signing.signingKey=" } 1' ORS='\\n' >> gradle.properties
```

**Comment by krzema12** [comment]
Hi Carlos, happy to see the plugin now supports Maven Central :) I'll take care of it within a week or so.

**Comment by krzema12** [comment]
Sonatype account and namespace already created: https://issues.sonatype.org/browse/OSSRH-45714
(2 years ago 🤣 it's high time to use it)

**Comment by krzema12** [comment]
```
> Task :signKotlinMultiplatformPublication FAILED
FAILURE: Build failed with an exception.


Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
* What went wrong:
Use '--warning-mode all' to show the individual deprecation warnings.
Execution failed for task ':signKotlinMultiplatformPublication'.
> Could not read PGP secret key
```

TODO: ensure the key format is correct.

**Comment by soywiz** [comment]
I faced that issue. When embedding in a gradle.properties file, it should be something like `\n-----BEGIN PGP PRIVATE KEY BLOCK------\n\n`, when using environment variables like on CI, you should actually put those line breaks (so it is a multiline environment variable AFAIK)

**Comment by krzema12** [comment]
Yeah, I used your one-liner and put it in the env var for CI :facepalm: Just `gpg --armor --export-secret-keys foobar@example.com` is enough and as you said, paste it verbatim for the CI variable.

**Comment by krzema12** [comment]
Next problem:

```
> Task :releaseMavenCentral
Trying to release groupId=it.krzeminski.vis-assert
Determined profileId=9279d4aa8eda10
Closing open repository RepoState(repositoryId=itkrzeminski-1000, type=open, notifications=0, transitioning=false)
Closing open repository RepoState(repositoryId=itkrzeminski-1001, type=open, notifications=0, transitioning=false)
Closing open repository RepoState(repositoryId=itkrzeminski-1002, type=open, notifications=0, transitioning=false)
Closing open repository RepoState(repositoryId=itkrzeminski-1003, type=open, notifications=0, transitioning=false)
Waiting transition RepoState(repositoryId=itkrzeminski-1000, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1001, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1002, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1003, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1000, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1001, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1002, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1003, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1000, type=open, notifications=1, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1001, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1002, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1003, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1000, type=open, notifications=1, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1001, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1002, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1003, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1000, type=open, notifications=1, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1001, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1002, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1003, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1000, type=open, notifications=1, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1001, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1002, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1003, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1000, type=open, notifications=1, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1001, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1002, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1003, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1000, type=open, notifications=2, transitioning=true)
Dropping release because of error state.notifications=RepoState(repositoryId=itkrzeminski-1001, type=open, notifications=3, transitioning=false)
Waiting transition RepoState(repositoryId=itkrzeminski-1002, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1003, type=open, notifications=0, transitioning=true)
Dropping release because of error state.notifications=RepoState(repositoryId=itkrzeminski-1000, type=open, notifications=3, transitioning=false)
Waiting transition RepoState(repositoryId=itkrzeminski-1002, type=open, notifications=0, transitioning=true)
Dropping release because of error state.notifications=RepoState(repositoryId=itkrzeminski-1003, type=open, notifications=3, transitioning=false)
Waiting transition RepoState(repositoryId=itkrzeminski-1002, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1002, type=open, notifications=0, transitioning=true)
Waiting transition RepoState(repositoryId=itkrzeminski-1002, type=open, notifications=3, transitioning=true)
Dropping release because of error state.notifications=RepoState(repositoryId=itkrzeminski-1002, type=open, notifications=3, transitioning=false)
Completed

> Task :releaseMavenCentral FAILED
```

Any idea where are some error details?

**Comment by soywiz** [comment]
To figure out, ~remove~ do not call the `releaseMavenCentral` task (that is the one that actually publish the staged files). Then perform a manual publish of the staged files at https://oss.sonatype.org/
There you will be able to check the actual errors.
I should update easy to dump the notifications there, but didn't do that yet :)

Have you uploaded your GPG sign to a key server? https://gist.github.com/kag0/fb6b7ce0816b77fe8349#publish-key

**Comment by krzema12** [comment]
Thanks, I published the keys and now trying without `releaseMavenCentral`. I'm just after the three platform-specific steps that stage the artifacts. Is it intended that three repositories appear in Nexus UI?

![image](https://user-images.githubusercontent.com/3110813/111042471-df59ae00-843d-11eb-8fc2-aa281f48161f.png)

I cannot select all of them and then click "Promote" or "Release". Let me try with promoting just a single one.

**Comment by krzema12** [comment]
I noticed what's wrong:

![image](https://user-images.githubusercontent.com/3110813/111042538-1e87ff00-843e-11eb-87bb-5511e921cf2f.png)

Working on it (I cannot promote or release any repo).

**Comment by krzema12** [comment]
https://issues.sonatype.org/browse/OSSRH-50493

> You can ignore that IQ Server Data recorded error. The IQ integration on oss.sonatype.org isn't even enabled.
> Your staging repository is in an open state, so you can continue with this section of our docs:
> https://central.sonatype.org/pages/releasing-the-deployment.html

And according to https://www.albertgao.xyz/2018/01/18/how-to-publish-artifact-to-maven-central-via-gradle/, I should "Close" the repositories - pretty counter-intuitive name. And then "Release".

Looks like it succeeded (no errors, the repositories eventually disappeared after releasing), but I cannot find the package on https://search.maven.org/. Maybe it takes time to index stuff. Let's see tomorrow.

**Comment by krzema12** [comment]
It has arrived: https://repo1.maven.org/maven2/it/krzeminski/vis-assert/
@soywiz please try to re-enable the code that uses vis-assert. And thanks for your help! :) I'm tempted to write down simplified steps and contribute to your plugin's README again.

**Comment by soywiz** [comment]
So no errors? Only warnings? I should check how the plugin handles this.

Yeah, the whole process is a bit cumbersome. But well in the end the closing is for freezing what you have uploaded and verify that everything follows the rules.

Nice to the README part, thanks!

BTW: artifacts usually are available in 10 minutes, and search.maven.org usually take 2 hours

**Comment by krzema12** [comment]
@soywiz In the meantime I published the key, so maybe it fixed the issue. In the following days I'll restore the last publishing step to make it fully automatic again and will check if it works fine. 

Leaving the issue open to:
[x] restore automatic publishing
[ ] remove leftover after Bintray
[] secrets
[] pieces of deployment script
[] replace with Maven badge if exists
[] adjust  installation guide

**Comment by krzema12** [comment]
@soywiz I redeployed as 0.4.1-beta and works like a charm! This plugin is awesome, does all the heavy lifting and exposes only what's necessary. I'm going to extract fsynth's common logic as a multiplatform project.

**Comment by soywiz** [comment]
👏 awesome, glad it helped! 😊
